apiVersion: v1
kind: Pod
metadata:
  name: fiap-lanchonete-service
spec:
  containers:
    - name: fiap-lanchonete-service
      image: fiap-lanchonete-service-lanchonete:latest
      imagePullPolicy: Never
      ports:
        - containerPort: 8080
      env:
        - name: MONGO_URL
          valueFrom:
            configMapKeyRef:
              name: db-config
              key: MONGO_URL
